# test urls
rahul = "https://rahulshettyacademy.com/AutomationPractice/"
nopcom = "https://demo.nopcommerce.com/"
orange = "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
fb = "https://www.facebook.com/"
google = "https://www.google.com/"
heroku = "https://the-internet.herokuapp.com/"
testauto = "https://testautomationpractice.blogspot.com/"
click_tets = "https://skill-test.net/mouse-double-click"
